"""
Project Value page.
"""

import sys
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from app.mlflow_loader import get_mlflow_client, get_all_runs, load_deliverable
from src.project_pricing import (
    PACKAGES,
    estimate_project_price,
    get_market_comparison,
)
from src.value_estimation import (
    calculate_project_roi,
    estimate_value_generated,
    format_currency,
    generate_value_summary,
)

st.set_page_config(page_title="Project Value", layout="wide")


def load_model_lift():
    """Load revenue lift from latest hierarchical run."""
    try:
        client = get_mlflow_client()
        runs = get_all_runs(client, model_type="hierarchical")
        if runs:
            run_id = runs[0]["run_id"]
            data = load_deliverable(run_id, "revenue_lift", client)
            return data.get("revenue_lift", data)
    except Exception:
        pass
    return None


def main():
    st.title("Project Value & ROI")
    st.markdown("Estimate the value generated by MMM optimization")
    st.markdown("---")

    # Sidebar inputs
    st.sidebar.subheader("Configuration")

    currency = st.sidebar.selectbox(
        "Currency",
        options=["USD", "GBP", "EUR", "BRL"],
        index=0,
    )

    annual_budget = st.sidebar.number_input(
        "Annual Marketing Budget",
        min_value=10000,
        max_value=100000000,
        value=1000000,
        step=50000,
        format="%d",
    )

    # Load model lift or use default
    model_lift = load_model_lift()
    default_lift = model_lift.get("lift_pct", 10.0) if model_lift else 10.0

    lift_pct = st.sidebar.slider(
        "Projected Lift (%)",
        min_value=1.0,
        max_value=50.0,
        value=float(default_lift),
        step=0.5,
    )

    st.sidebar.markdown("---")

    package = st.sidebar.selectbox(
        "Project Package",
        options=list(PACKAGES.keys()),
        format_func=lambda x: PACKAGES[x]["name"],
        index=2,
    )

    # Main content
    col1, col2 = st.columns([2, 1])

    with col1:
        st.subheader("Value Analysis")

        # Generate summary for all confidence levels
        pricing = estimate_project_price(package=package)
        project_cost = pricing["total"]

        summary = generate_value_summary(annual_budget, lift_pct, project_cost)

        # Display as table
        summary_data = []
        for conf, data in summary.items():
            summary_data.append({
                "Confidence": conf.title(),
                "Adjusted Lift": f"{data['adjusted_lift_pct']:.1f}%",
                "Annual Gain": format_currency(data["annual_gain"], currency),
                "ROI (3 Years)": f"{data['roi_3y']:.0f}%",
                "Payback": f"{data['payback_months']:.1f} months",
            })

        st.dataframe(pd.DataFrame(summary_data), use_container_width=True, hide_index=True)

        # Detailed calculation with selected confidence
        st.markdown("---")
        confidence = st.radio(
            "Analysis Confidence Level",
            options=["conservative", "moderate", "optimistic"],
            horizontal=True,
            index=0,
        )

        value = estimate_value_generated(annual_budget, lift_pct, confidence)
        roi = calculate_project_roi(value, project_cost)

        # KPIs
        c1, c2, c3, c4 = st.columns(4)

        c1.metric(
            "Annual Gain",
            format_currency(value["annual_gain"], currency),
            f"{value['adjusted_lift_pct']:.1f}% lift",
        )
        c2.metric(
            "3-Year ROI",
            f"{roi['roi_pct']:.0f}%",
            f"{format_currency(roi['net_gain'], currency)} net",
        )
        c3.metric(
            "Payback Period",
            f"{roi['payback_months']:.1f} mo",
        )
        c4.metric(
            "Project Cost",
            format_currency(project_cost, currency),
        )

        # Chart: Yearly gains
        st.markdown("---")
        st.subheader("Projected Value Over Time")

        fig = go.Figure()

        years = list(range(1, len(roi["yearly_gains"]) + 1))
        cumulative = []
        total = 0
        for g in roi["yearly_gains"]:
            total += g
            cumulative.append(total)

        fig.add_trace(go.Bar(
            x=years,
            y=roi["yearly_gains"],
            name="Annual Gain",
            marker_color="steelblue",
        ))

        fig.add_trace(go.Scatter(
            x=years,
            y=cumulative,
            name="Cumulative",
            mode="lines+markers",
            marker_color="coral",
        ))

        fig.add_hline(
            y=project_cost,
            line_dash="dash",
            line_color="gray",
            annotation_text="Project Cost",
        )

        fig.update_layout(
            xaxis_title="Year",
            yaxis_title=f"Value ({currency})",
            height=350,
            legend=dict(orientation="h", yanchor="bottom", y=1.02),
        )

        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("Project Pricing")

        # Package details
        st.markdown(f"**Package:** {pricing['package']}")

        for comp in pricing["components"]:
            st.markdown(f"- {comp['name']}: {format_currency(comp['price'], currency)}")

        st.markdown("---")
        st.markdown(f"**Subtotal:** {format_currency(pricing['subtotal'], currency)}")
        st.markdown(f"**Discount ({pricing['discount_pct']}%):** -{format_currency(pricing['discount_amount'], currency)}")
        st.markdown(f"**Total:** {format_currency(pricing['total'], currency)}")

        # Market comparison
        st.markdown("---")
        st.subheader("Market Comparison")

        comparison = get_market_comparison()
        for item in comparison:
            with st.expander(item["provider"]):
                st.markdown(f"**Type:** {item['type']}")
                st.markdown(f"**Price:** {item['price_range']}")
                st.markdown(f"**Timeline:** {item['timeline']}")

    # Insight box
    st.markdown("---")

    if roi["payback_months"] < 12:
        st.success(
            f"This project pays for itself in **{roi['payback_months']:.1f} months**. "
            f"With a 3-year ROI of **{roi['roi_pct']:.0f}%**, this represents excellent value."
        )
    else:
        st.info(
            f"Payback period is **{roi['payback_months']:.1f} months**. "
            f"Consider a higher marketing budget or optimistic confidence level for faster ROI."
        )


if __name__ == "__main__":
    main()
else:
    main()
