"""
Value estimation module.

Calculates projected value from MMM optimization recommendations.
"""

from __future__ import annotations

from typing import Literal


# Industry benchmarks for MMM efficiency improvements
EFFICIENCY_BENCHMARKS = {
    "conservative": 0.10,   # 10% improvement
    "moderate": 0.15,       # 15% improvement
    "optimistic": 0.20,     # 20% improvement
    "aggressive": 0.30,     # 30% improvement
}

# Confidence adjustments for projections
CONFIDENCE_MULTIPLIERS = {
    "conservative": 0.50,   # Use 50% of projected lift
    "moderate": 0.75,       # Use 75% of projected lift
    "optimistic": 1.00,     # Use 100% of projected lift
}


def estimate_value_generated(
    annual_budget: float,
    lift_pct: float,
    confidence: Literal["conservative", "moderate", "optimistic"] = "conservative",
) -> dict:
    """
    Estimate annual value generated by MMM optimization.

    Args:
        annual_budget: Total annual marketing budget.
        lift_pct: Projected lift percentage from model (deliverable 8).
        confidence: Confidence level for adjustment.

    Returns:
        Dict with value estimation details.
    """
    multiplier = CONFIDENCE_MULTIPLIERS.get(confidence, 0.5)
    adjusted_lift = lift_pct * multiplier
    annual_gain = annual_budget * (adjusted_lift / 100)

    return {
        "annual_budget": annual_budget,
        "raw_lift_pct": lift_pct,
        "confidence_level": confidence,
        "confidence_multiplier": multiplier,
        "adjusted_lift_pct": adjusted_lift,
        "annual_gain": annual_gain,
        "monthly_gain": annual_gain / 12,
        "quarterly_gain": annual_gain / 4,
    }


def calculate_project_roi(
    value_estimation: dict,
    project_cost: float,
    years: int = 3,
    annual_decay: float = 0.90,
) -> dict:
    """
    Calculate project ROI and payback period.

    Args:
        value_estimation: Output from estimate_value_generated.
        project_cost: Total project cost.
        years: Number of years to calculate total gain.
        annual_decay: Year-over-year decay of benefits.

    Returns:
        Dict with ROI metrics.
    """
    annual_gain = value_estimation["annual_gain"]

    # Calculate multi-year gains with decay
    yearly_gains = []
    for year in range(years):
        gain = annual_gain * (annual_decay ** year)
        yearly_gains.append(gain)

    total_gain = sum(yearly_gains)
    net_gain = total_gain - project_cost

    # ROI calculation
    roi_pct = (net_gain / project_cost * 100) if project_cost > 0 else 0

    # Payback period
    if annual_gain > 0:
        payback_months = (project_cost / annual_gain) * 12
    else:
        payback_months = float("inf")

    return {
        "project_cost": project_cost,
        "annual_gain": annual_gain,
        "yearly_gains": yearly_gains,
        "total_gain": total_gain,
        "net_gain": net_gain,
        "roi_pct": roi_pct,
        "payback_months": payback_months,
        "years_analyzed": years,
    }


def generate_value_summary(
    annual_budget: float,
    lift_pct: float,
    project_cost: float,
) -> dict:
    """
    Generate complete value analysis with all confidence levels.

    Args:
        annual_budget: Total annual marketing budget.
        lift_pct: Projected lift from model.
        project_cost: Total project cost.

    Returns:
        Dict with value analysis for each confidence level.
    """
    results = {}

    for confidence in ["conservative", "moderate", "optimistic"]:
        value = estimate_value_generated(annual_budget, lift_pct, confidence)
        roi = calculate_project_roi(value, project_cost)

        results[confidence] = {
            "adjusted_lift_pct": value["adjusted_lift_pct"],
            "annual_gain": value["annual_gain"],
            "roi_3y": roi["roi_pct"],
            "payback_months": roi["payback_months"],
        }

    return results


def format_currency(value: float, currency: str = "USD") -> str:
    """Format value as currency."""
    if currency == "USD":
        return f"${value:,.0f}"
    elif currency == "GBP":
        return f"£{value:,.0f}"
    elif currency == "EUR":
        return f"€{value:,.0f}"
    elif currency == "BRL":
        return f"R${value:,.0f}"
    return f"{value:,.0f}"
